#!/usr/bin/env python3
"""Refuse a commit that carries a secret, a path into someone's home directory, a private mailbox, or the
maintainers' internal build-record jargon. GENERATED by the maintainers' export from their own scanner, which carries
further pattern lists that stay private — edit it there, not here.
Usage: public_scan_ci.py <repo-root> [files...]      (no files → all tracked files). Exit 1 on any hit.
       public_scan_ci.py --history <repo-root>       git metadata: every commit's author EMAIL against the
                                                     PRIVATE_EMAIL shape, and any `Claude-Session:` trailer line.
       public_scan_ci.py --ast <repo-root> [files-or-dirs...]
                                                     tokenizer/AST mode: comments, docstrings and string literals only
                                                     (identifiers and code are never scanned). A directory scans every
                                                     .py under it.
The per-file allowances are inline (SITE_ALLOW below); no allow file is read. CI runs the file scan and the history
scan on every push."""
import ast, io, re, subprocess, sys, tokenize
from pathlib import Path


SECRETS = [r"sk-[A-Za-z0-9]{20,}", r"ghp_[A-Za-z0-9]{20,}", r"AKIA[0-9A-Z]{16}", r"BEGIN (RSA|OPENSSH) PRIVATE"]
# Shapes, not names: a path into a home directory, and a private mailbox (an author line should carry the
# GitHub noreply address, which is public anyway).
MAILBOX = r"@(gmail|googlemail|hotmail|outlook|live|yahoo|icloud|proton|protonmail|gmx|aol|yandex|fastmail)\.[a-z]{2,}"
LOCAL = [r"/home/[A-Za-z]", r"/Users/[A-Za-z]", r"[A-Za-z0-9._%+-]+" + MAILBOX]
# Internal build-record jargon — plan names, task numbers, review rounds, rulings, numbered findings — cites a
# record that is not published and means nothing to a reader of this repository.
BUILD_RECORD = [r"\bPlan [AB]\b", r"\bTask \d+\b", r"\bTask-\d+\b", r"fix round", r"Controller ruling",
                r"\bfinding #", r"\bI\d guard\b", r"\bPoC\b", r"fifth-term guard"]
CATEGORIES = (("secret", SECRETS), ("local", LOCAL), ("build-record", BUILD_RECORD))
ALLOW: dict[str, list[str]] = {}                          # whole patterns silenced per file (line mode); none needed
# Per-file allowances, each silencing ONE term in ONE file (`term_allowed`): a shaped fixture in a test is not a
# secret, and this file's own pattern sources are not citations.
SITE_ALLOW = [
    ("tests/substrate/test_secret_guard.py", r"AKIAABCDEFGHIJKLMNOP"),
    ("tests/substrate/test_secret_guard.py", r"BEGIN RSA PRIVATE"),
    ("scripts/public_scan_ci.py", r"fix round"),
    ("scripts/public_scan_ci.py", r"Controller ruling"),
    ("scripts/public_scan_ci.py", r"fifth-term guard"),
    ("scripts/public_scan_ci.py", r"AKIAABCDEFGHIJKLMNOP"),
    ("scripts/public_scan_ci.py", r"BEGIN RSA PRIVATE"),
]
SESSION_TRAILER = "Claude-Session:"                         # a link to a private session: provenance in metadata
PRIVATE_EMAIL = [MAILBOX + "$"]                             # author emails (--history) are checked against this shape


def tracked(root: Path) -> list[Path]:
    out = subprocess.run(["git", "ls-files"], cwd=root, capture_output=True, text=True, check=True).stdout
    return [root / p for p in out.split()]


def scan_files(root: Path, files: list[Path], allow_file: str | None = None) -> int:
    """Line mode: every pattern, every match, whole file. The per-file allowances apply here exactly as in
    --ast (same file, same per-TERM semantics via `term_allowed`), so a product constant allowed for one file
    passes the pre-commit hook and the export's line scan too — and still hits in every other file."""
    allow = load_site_allow(root, allow_file)
    hits = 0
    for f in files:
        if not f.is_file():
            continue
        rel = str(f.resolve().relative_to(root))
        allowed = ALLOW.get(rel, [])
        try:
            text = f.read_text(errors="ignore")
        except OSError as e:
            print(f"{rel}:0: unreadable: {e}")
            hits += 1
            continue
        for kind, pats in CATEGORIES:
            for p in pats:
                if p in allowed:
                    continue
                for m in re.finditer(p, text):
                    if term_allowed(rel, m.group(0), allow):
                        continue
                    line = text.count("\n", 0, m.start()) + 1
                    print(f"{rel}:{line}: {kind}: {m.group(0)!r}")
                    hits += 1
    return hits


def scan_history(root: Path) -> int:
    """Every commit reachable from HEAD. The author EMAIL is checked against PRIVATE_EMAIL; the author NAME is
    not (the GitHub handle is public in the repo URL, and so is the noreply address that carries it). Any
    `Claude-Session:` line in a message is a hit."""
    try:
        out = subprocess.run(["git", "log", "--format=%H%x00%ae%x00%B%x1e"], cwd=root,
                             capture_output=True, text=True, check=True).stdout
    except subprocess.CalledProcessError as e:
        print(f"git log failed: {e.stderr.strip()}")
        return 1
    hits = 0
    for rec in out.split("\x1e"):
        rec = rec.strip("\n")
        if not rec:
            continue
        sha, email, body = rec.split("\x00", 2)
        if any(re.search(p, email) for p in PRIVATE_EMAIL):
            print(f"{sha[:12]}: author email: {email!r}")
            hits += 1
        for line in body.splitlines():
            if line.startswith(SESSION_TRAILER):
                print(f"{sha[:12]}: trailer: {line.strip()!r}")
                hits += 1
    return hits


def load_site_allow(root: Path, allow_file: str | None = None) -> list[tuple[str, "re.Pattern"]]:
    """The per-file allowances are SITE_ALLOW, compiled. No file is read: `allow_file` is kept for the callers'
    signature and ignored."""
    return [(path, re.compile(pat)) for path, pat in SITE_ALLOW]


def term_allowed(rel: str, term: str, allow: list[tuple[str, "re.Pattern"]]) -> bool:
    """The one allow check both modes use: an entry silences a hit only when its path is THIS file and its
    regex matches the specific TERM the scan pattern matched — never the surrounding line or site."""
    return any(rel == ap and ar.search(term) for ap, ar in allow)


def _sites(src: str):
    """Yield (lineno, kind, text) for every comment, docstring and string literal. Code is not yielded."""
    for tok in tokenize.generate_tokens(io.StringIO(src).readline):
        if tok.type == tokenize.COMMENT:
            yield tok.start[0], "comment", tok.string
    tree = ast.parse(src)
    doc_nodes = set()
    for node in ast.walk(tree):
        if isinstance(node, (ast.Module, ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)):
            if node.body and isinstance(node.body[0], ast.Expr) and isinstance(node.body[0].value, ast.Constant) \
                    and isinstance(node.body[0].value.value, str):
                doc_nodes.add(id(node.body[0].value))
                yield node.body[0].value.lineno, "docstring", node.body[0].value.value
    for node in ast.walk(tree):
        if isinstance(node, ast.Constant) and isinstance(node.value, (str, bytes)) and id(node) not in doc_nodes:
            # A bytes literal (b"...") is a string literal for this scan too — a secret
            # hidden in one must not be invisible. Decode leniently; this is provenance-scanning, not I/O.
            text = node.value if isinstance(node.value, str) else node.value.decode("utf-8", errors="replace")
            yield node.lineno, "string", text


def scan_ast(root: Path, files: list[str], allow_file: str | None = None) -> int:
    allow = load_site_allow(root, allow_file)
    hits = 0
    # A positional may be a file or a DIRECTORY: a directory scans every .py under it (recursively, skipping
    # .venv/.git), so `--ast <root> src/pkg` means what it says instead of reporting `Is a directory` as a hit.
    paths: list[Path] = []
    for f in files:
        p = Path(f)
        q = p if p.is_absolute() else root / p
        if q.is_dir():
            paths.extend(sorted(x.relative_to(root) for x in q.rglob("*.py")
                                if ".venv" not in x.parts and ".git" not in x.parts))
        else:
            paths.append(p)
    if not files:
        paths = [p for p in root.rglob("*.py") if ".venv" not in p.parts and ".git" not in p.parts]
    for p in paths:
        rel = str(p.relative_to(root)) if p.is_absolute() else str(p)
        try:
            # ValueError covers UnicodeDecodeError (non-UTF-8 bytes) and the older
            # null-byte case — report the file as a hit and keep scanning the rest of the run.
            src = (root / rel).read_text()
            sites = list(_sites(src))
        except (OSError, SyntaxError, tokenize.TokenError, ValueError) as e:
            print(f"{rel}: cannot parse or read: {e}"); hits += 1; continue
        for lineno, kind, text in sites:
            # One hit per site: report the first term that matches and is not allowlisted.
            # An allow entry covers only the specific matched term (m.group(0)) it was written
            # against, never the whole site's text — so a genuine, non-allowlisted hit co-located with
            # an allowed one in the same comment/docstring/string still fires.
            matched = False
            for cat, pats in CATEGORIES:
                if matched:
                    break
                for pat in pats:
                    m = re.search(pat, text)
                    if not m or term_allowed(rel, m.group(0), allow):
                        continue
                    print(f"{rel}:{lineno}: {cat} {m.group(0)!r} in {kind}")
                    hits += 1
                    matched = True
                    break
    return hits


def main() -> int:
    args = sys.argv[1:]
    history = "--history" in args
    ast_mode = "--ast" in args
    allow_file = None
    args = [a for a in args if a not in ("--history", "--ast")]
    if not args:
        print(__doc__)
        return 2
    root = Path(args[0]).resolve()
    if history:
        hits = scan_history(root)
        print("public_scan --history: clean" if not hits else f"public_scan --history: {hits} hit(s) — push refused")
    elif ast_mode:
        hits = scan_ast(root, args[1:], allow_file)
        print("public_scan --ast: clean" if not hits else f"public_scan --ast: {hits} hit(s)")
    else:
        files = [Path(f) for f in args[1:]] or tracked(root)
        hits = scan_files(root, files, allow_file)
        print("public_scan: clean" if not hits else f"public_scan: {hits} hit(s) — commit refused")
    return 1 if hits else 0


if __name__ == "__main__":
    sys.exit(main())
